### ISSUE TITLE
Cannot choose format for Poly.download 

### ISSUE THREAD

**Issue by skpinelabs** [piemonte/Poly#3]
`Poly.download(asset: [...])` just returns the first defined format for the asset. It should have a parameter to choose the asset type, as usually `.gltf` is returned which is not that usable in IOS.

**Comment by skpinelabs** [comment]
I made a draft PR, which works for me in the IOS app I'm working on: https://github.com/piemonte/Poly/pull/4

I'd be happy to get feedback from you to make it clean and mergeable to master.

**Comment by piemonte** [comment]
@skpinelabs thanks again for the PR. i made a couple minor changes to your update on master, ie. adopted a Format type. 👍
